from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import JSON, Enum, Float, ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class MeetingStatus(enum.StrEnum):
    QUEUED = "queued"
    PROCESSING = "processing"
    TRANSCRIBING = "transcribing"
    EXTRACTING = "extracting"
    SUMMARIZING = "summarizing"
    DONE = "done"
    ERROR = "error"


class TaskStatus(enum.StrEnum):
    DRAFT = "draft"
    APPROVED = "approved"
    DONE = "done"
    REJECTED = "rejected"


class TaskPriority(enum.StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class BriefStatus(enum.StrEnum):
    EMPTY = "empty"          # no brief generated yet
    PROCESSING = "processing"  # generation in flight
    READY = "ready"          # brief generated and current
    ERROR = "error"          # last generation failed


class KnowledgeStatus(enum.StrEnum):
    EMPTY = "empty"          # no brief generated yet
    PROCESSING = "processing"  # Init job running
    READY = "ready"          # brief generated and current
    ERROR = "error"          # last Init failed


class Project(Base):
    __tablename__ = "projects"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(200))
    color: Mapped[str] = mapped_column(String(20), default="#7a0d38")
    description: Mapped[str] = mapped_column(Text, default="")
    ai_context: Mapped[str] = mapped_column(Text, default="")  # editable source description; input to Init, not injected directly
    # Distilled knowledge brief — the ONLY knowledge text injected into extraction.
    # Generated by the Init job from ai_context + knowledge_files (see app/llm/distill.py).
    knowledge_brief: Mapped[str] = mapped_column(Text, default="")
    knowledge_status: Mapped[KnowledgeStatus] = mapped_column(
        Enum(KnowledgeStatus, values_callable=lambda e: [m.value for m in e]),
        default=KnowledgeStatus.EMPTY,
    )
    knowledge_error: Mapped[str | None] = mapped_column(Text, default=None)
    knowledge_generated_at: Mapped[datetime | None] = mapped_column(default=None)
    # Bumped whenever a source (ai_context or a knowledge file) changes; used to flag a
    # stale brief when sources changed after the last generation.
    knowledge_sources_changed_at: Mapped[datetime | None] = mapped_column(default=None)
    task_prefix: Mapped[str] = mapped_column(String(20), default="")  # e.g. "CRM"
    task_format: Mapped[str] = mapped_column(Text, default="")  # task description template
    # Language for extracted task titles/descriptions: "auto" = language of the meeting,
    # otherwise an ISO 639-1 code (e.g. "uk", "en") the LLM is told to write in.
    task_language: Mapped[str] = mapped_column(String(20), default="auto")
    # Area/sub-area taxonomy ("[Area][Sub-area]" strings) used for Jira ticket titles/labels.
    # Auto-filled by Init from the knowledge sources (component map); user-editable.
    task_areas: Mapped[list[str]] = mapped_column(JSON, default=list)
    glossary: Mapped[list[str]] = mapped_column(JSON, default=list)
    team: Mapped[list[dict[str, str]]] = mapped_column(JSON, default=list)  # items: {"name", "role"}
    # Jira ticket-template config (Feature B):
    jira_static_labels: Mapped[list[str]] = mapped_column(JSON, default=list)  # e.g. ["aware-created-by-robots"]
    jira_demo_label: Mapped[bool] = mapped_column(default=False)  # add demo-<YYYY-MM-DD> from meeting date
    jira_sprint_field: Mapped[str] = mapped_column(String(50), default="")  # e.g. "customfield_10020"; blank = skip
    jira_sprint_id: Mapped[int | None] = mapped_column(default=None)
    jira_enabled: Mapped[bool] = mapped_column(default=False)
    jira_key: Mapped[str] = mapped_column(String(50), default="")
    jira_base_url: Mapped[str] = mapped_column(String(500), default="")  # e.g. https://acme.atlassian.net
    jira_email: Mapped[str] = mapped_column(String(300), default="")
    jira_api_token: Mapped[str] = mapped_column(String(500), default="")  # stored plaintext locally; never returned by the API
    llm_provider: Mapped[str] = mapped_column(String(50), default="lmstudio")
    llm_model: Mapped[str] = mapped_column(String(200), default="local-model")
    # IPv4 loopback on purpose: `localhost` resolves to `::1` first on macOS while
    # LM Studio listens on IPv4 only (same bug class as frontend/src/lib/api.ts).
    llm_base_url: Mapped[str | None] = mapped_column(String(500), default="http://127.0.0.1:1234/v1")
    llm_api_key: Mapped[str | None] = mapped_column(String(500), default=None)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())

    @property
    def knowledge_stale(self) -> bool:
        """True when a source changed after the brief was last generated."""
        changed = self.knowledge_sources_changed_at
        if changed is None:
            return False
        generated = self.knowledge_generated_at
        return generated is None or changed > generated

    @property
    def jira_token_set(self) -> bool:
        return bool(self.jira_api_token)

    @property
    def jira_token_hint(self) -> str:
        return self.jira_api_token[-4:] if self.jira_api_token else ""

    meetings: Mapped[list[Meeting]] = relationship(back_populates="project")
    knowledge_files: Mapped[list[KnowledgeFile]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )


class KnowledgeFile(Base):
    """A source file (PDF or text) uploaded to a project's knowledge base.

    Files are raw inputs to the Init distillation job; the resulting brief lives
    on Project.knowledge_brief, not here.
    """

    __tablename__ = "knowledge_files"

    id: Mapped[int] = mapped_column(primary_key=True)
    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"), index=True)
    filename: Mapped[str] = mapped_column(String(300))
    path: Mapped[str] = mapped_column(String(1000))
    kind: Mapped[str] = mapped_column(String(10))  # "pdf" | "text"
    size_bytes: Mapped[int] = mapped_column(default=0)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    project: Mapped[Project] = relationship(back_populates="knowledge_files")


class Meeting(Base):
    __tablename__ = "meetings"

    id: Mapped[int] = mapped_column(primary_key=True)
    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"), index=True)
    title: Mapped[str] = mapped_column(String(300))
    source_filename: Mapped[str] = mapped_column(String(300))
    media_path: Mapped[str] = mapped_column(String(1000))
    status: Mapped[MeetingStatus] = mapped_column(
        Enum(MeetingStatus, values_callable=lambda e: [m.value for m in e]),
        default=MeetingStatus.QUEUED,
    )
    error_message: Mapped[str | None] = mapped_column(Text, default=None)
    duration_sec: Mapped[float | None] = mapped_column(Float, default=None)
    language: Mapped[str | None] = mapped_column(String(10), default=None)
    progress: Mapped[float | None] = mapped_column(Float, default=None)
    processing_started_at: Mapped[datetime | None] = mapped_column(default=None)
    processing_finished_at: Mapped[datetime | None] = mapped_column(default=None)
    # {"SPEAKER_00": "Andriy Tretiak", ...} — user-confirmed mapping of diarization
    # labels to Project.team names. Empty until the user assigns them in the UI.
    speaker_labels: Mapped[dict[str, str]] = mapped_column(JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    project: Mapped[Project] = relationship(back_populates="meetings")
    segments: Mapped[list[TranscriptSegment]] = relationship(
        back_populates="meeting", order_by="TranscriptSegment.t_start", cascade="all, delete-orphan"
    )
    tasks: Mapped[list[Task]] = relationship(back_populates="meeting")
    brief: Mapped[MeetingBrief | None] = relationship(
        back_populates="meeting", cascade="all, delete-orphan", uselist=False
    )

    @property
    def detected_speakers(self) -> list[str]:
        """Sorted unique diarization labels present in this meeting's transcript."""
        return sorted({s.speaker for s in self.segments if s.speaker})


class MeetingBrief(Base):
    """Structured minutes for one meeting: what was decided, what is at risk,
    what is still open. Generated after task extraction (see app/llm/brief.py).

    List columns hold `[{"text": str, "source_timestamp": float | None}, ...]`
    so every point can deep-link into the video like Task.source_timestamp does.
    """

    __tablename__ = "meeting_briefs"

    id: Mapped[int] = mapped_column(primary_key=True)
    meeting_id: Mapped[int] = mapped_column(ForeignKey("meetings.id"), index=True, unique=True)
    summary: Mapped[str] = mapped_column(Text, default="")
    decisions: Mapped[list[dict]] = mapped_column(JSON, default=list)
    risks: Mapped[list[dict]] = mapped_column(JSON, default=list)
    open_questions: Mapped[list[dict]] = mapped_column(JSON, default=list)
    next_steps: Mapped[list[dict]] = mapped_column(JSON, default=list)
    status: Mapped[BriefStatus] = mapped_column(
        Enum(BriefStatus, values_callable=lambda e: [m.value for m in e]),
        default=BriefStatus.EMPTY,
    )
    error: Mapped[str | None] = mapped_column(Text, default=None)
    generated_at: Mapped[datetime | None] = mapped_column(default=None)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    meeting: Mapped[Meeting] = relationship(back_populates="brief")


class TranscriptSegment(Base):
    __tablename__ = "transcript_segments"

    id: Mapped[int] = mapped_column(primary_key=True)
    meeting_id: Mapped[int] = mapped_column(ForeignKey("meetings.id"), index=True)
    t_start: Mapped[float] = mapped_column(Float)
    t_end: Mapped[float] = mapped_column(Float)
    text: Mapped[str] = mapped_column(Text)
    speaker: Mapped[str | None] = mapped_column(String(100), default=None)  # raw diarization label

    meeting: Mapped[Meeting] = relationship(back_populates="segments")

    @property
    def speaker_display(self) -> str | None:
        """Mapped team name when the user confirmed it, else the raw label."""
        return display_speaker(self.meeting, self.speaker)


def display_speaker(meeting: Meeting, raw: str | None) -> str | None:
    """Mapped team name when the user confirmed it, else the raw diarization label."""
    if not raw:
        return None
    return meeting.speaker_labels.get(raw) or raw


class Task(Base):
    __tablename__ = "tasks"

    id: Mapped[int] = mapped_column(primary_key=True)
    project_id: Mapped[int] = mapped_column(ForeignKey("projects.id"), index=True)
    meeting_id: Mapped[int | None] = mapped_column(ForeignKey("meetings.id"), index=True, default=None)
    title: Mapped[str] = mapped_column(String(500))
    description: Mapped[str] = mapped_column(Text, default="")
    # "[Area][Sub-area]" chosen from the project's task_areas; drives Jira title/labels. Editable at review.
    area: Mapped[str] = mapped_column(String(200), default="")
    # Extra per-task Jira labels, merged with the derived ones (static/demo/area). Editable at review.
    labels: Mapped[list[str]] = mapped_column(JSON, default=list)
    assignee: Mapped[str | None] = mapped_column(String(200), default=None)
    priority: Mapped[TaskPriority] = mapped_column(
        Enum(TaskPriority, values_callable=lambda e: [m.value for m in e]),
        default=TaskPriority.MEDIUM,
    )
    status: Mapped[TaskStatus] = mapped_column(
        Enum(TaskStatus, values_callable=lambda e: [m.value for m in e]),
        default=TaskStatus.DRAFT,
    )
    source_timestamp: Mapped[float | None] = mapped_column(Float, default=None)
    jira_issue_key: Mapped[str | None] = mapped_column(String(50), default=None)  # e.g. CRM-42
    jira_synced_at: Mapped[datetime | None] = mapped_column(default=None)
    jira_sync_error: Mapped[str | None] = mapped_column(Text, default=None)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())

    meeting: Mapped[Meeting | None] = relationship(back_populates="tasks")
    screenshots: Mapped[list[TaskScreenshot]] = relationship(
        back_populates="task", order_by="TaskScreenshot.position", cascade="all, delete-orphan"
    )


class TaskScreenshot(Base):
    """A video frame captured near a task's source_timestamp.

    Files live under settings.screenshots_dir / <task_id>/; rows cascade with the
    task, but file unlink is explicit (see app/pipeline/screenshots.py helpers).
    """

    __tablename__ = "task_screenshots"

    id: Mapped[int] = mapped_column(primary_key=True)
    task_id: Mapped[int] = mapped_column(ForeignKey("tasks.id"), index=True)
    path: Mapped[str] = mapped_column(String(1000))
    t_sec: Mapped[float] = mapped_column(Float)  # actual (clamped) video time captured
    position: Mapped[int] = mapped_column(default=0)  # stable display order
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    task: Mapped[Task] = relationship(back_populates="screenshots")


class AppSetting(Base):
    """Global, app-wide settings (single row, id=1). Currently the base extraction prompt."""

    __tablename__ = "app_settings"

    id: Mapped[int] = mapped_column(primary_key=True)
    extraction_prompt: Mapped[str] = mapped_column(Text, default="")
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())
