"""meeting progress tracking

Revision ID: 20ee1c2aaaa1
Revises: e1e87c558201
Create Date: 2026-07-16 22:42:17.015647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ee1c2aaaa1'
down_revision: Union[str, Sequence[str], None] = 'e1e87c558201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('progress', sa.Float(), nullable=True))
    op.add_column('meetings', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'processing_started_at')
    op.drop_column('meetings', 'progress')
    # ### end Alembic commands ###
