/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meetings */
        get: operations["list_meetings_api_meetings_get"];
        put?: never;
        /** Upload Meeting */
        post: operations["upload_meeting_api_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meeting */
        get: operations["get_meeting_api_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        /** Delete Meeting */
        delete: operations["delete_meeting_api_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Meeting
         * @description Update the meeting's speaker-label mapping (diarization label → team name).
         *
         *     Merge semantics: only the labels present in the payload change; an empty value
         *     removes that label's mapping. Keys must be detected labels, values team names.
         */
        patch: operations["patch_meeting_api_meetings__meeting_id__patch"];
        trace?: never;
    };
    "/api/meetings/{meeting_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Meeting */
        post: operations["retry_meeting_api_meetings__meeting_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/reextract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reextract Meeting
         * @description Re-run task extraction on an already-processed meeting.
         *
         *     Drops this meeting's existing tasks and requeues the pipeline; transcription is
         *     skipped (segments already exist), so only extraction re-runs — useful after tuning
         *     the prompt or project AI context.
         */
        post: operations["reextract_meeting_api_meetings__meeting_id__reextract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{meeting_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Meeting Media
         * @description Stream the original uploaded recording for inline playback.
         *
         *     FileResponse honours HTTP Range requests, so the browser can seek without
         *     downloading the whole file.
         */
        get: operations["get_meeting_media_api_meetings__meeting_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Patch Task */
        patch: operations["patch_task_api_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/tasks/{task_id}/jira-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jira Preview */
        get: operations["jira_preview_api_tasks__task_id__jira_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/jira-push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Jira Push */
        post: operations["jira_push_api_tasks__task_id__jira_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/screenshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Screenshots */
        get: operations["list_screenshots_api_tasks__task_id__screenshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/screenshots/{screenshot_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screenshot Image */
        get: operations["get_screenshot_image_api_tasks__task_id__screenshots__screenshot_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/screenshots/{screenshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Screenshot
         * @description User curation from the approve dialog: drop one frame permanently.
         */
        delete: operations["delete_screenshot_api_tasks__task_id__screenshots__screenshot_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Project */
        patch: operations["patch_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/llm-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Llm Test */
        post: operations["llm_test_api_projects__project_id__llm_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/llm-connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Llm Connect
         * @description Probe the project's local LLM server and report the models it has loaded.
         *
         *     Unlike ``llm-test`` (a full chat round-trip through the LLM), this pings the
         *     OpenAI-compatible ``GET /v1/models`` endpoint with a short timeout so the UI
         *     can show an immediate reachability status and auto-fill the detected model.
         */
        post: operations["llm_connect_api_projects__project_id__llm_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/jira-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Jira Test */
        post: operations["jira_test_api_projects__project_id__jira_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/jira-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Jira Users
         * @description Assignable users of the project's Jira project, for the assignee picker.
         */
        get: operations["jira_users_api_projects__project_id__jira_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge */
        get: operations["get_knowledge_api_projects__project_id__knowledge_get"];
        put?: never;
        /** Upload Knowledge File */
        post: operations["upload_knowledge_file_api_projects__project_id__knowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/knowledge/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Knowledge File */
        delete: operations["delete_knowledge_file_api_projects__project_id__knowledge__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/knowledge/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Init Knowledge */
        post: operations["init_knowledge_api_projects__project_id__knowledge_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppSettingsOut */
        AppSettingsOut: {
            /** Extraction Prompt */
            extraction_prompt: string;
        };
        /** AppSettingsPatchIn */
        AppSettingsPatchIn: {
            /** Extraction Prompt */
            extraction_prompt?: string | null;
        };
        /** Body_upload_knowledge_file_api_projects__project_id__knowledge_post */
        Body_upload_knowledge_file_api_projects__project_id__knowledge_post: {
            /** File */
            file: string;
        };
        /** Body_upload_meeting_api_meetings_post */
        Body_upload_meeting_api_meetings_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
            /** Project Id */
            project_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JiraPreviewOut */
        JiraPreviewOut: {
            /** Ok */
            ok: boolean;
            /** Project Key */
            project_key?: string | null;
            /** Issue Type */
            issue_type?: string | null;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Priority */
            priority?: string | null;
            /**
             * Labels
             * @default []
             */
            labels: string[];
            /** Sprint Id */
            sprint_id?: number | null;
            /** Area */
            area?: string | null;
            /** Assignee Query */
            assignee_query?: string | null;
            /**
             * Assignee Found
             * @default false
             */
            assignee_found: boolean;
            /** Assignee Display Name */
            assignee_display_name?: string | null;
            /** Error */
            error?: string | null;
        };
        /** JiraTestOut */
        JiraTestOut: {
            /** Ok */
            ok: boolean;
            /** Account Name */
            account_name?: string | null;
            /** Error */
            error?: string | null;
        };
        /** JiraUserOut */
        JiraUserOut: {
            /** Account Id */
            account_id: string;
            /** Display Name */
            display_name: string;
        };
        /** JiraUsersOut */
        JiraUsersOut: {
            /** Ok */
            ok: boolean;
            /**
             * Users
             * @default []
             */
            users: components["schemas"]["JiraUserOut"][];
            /** Error */
            error?: string | null;
        };
        /** KnowledgeFileOut */
        KnowledgeFileOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Filename */
            filename: string;
            /** Kind */
            kind: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * KnowledgeStateOut
         * @description Knowledge-base status for a project, returned alongside its files.
         */
        KnowledgeStateOut: {
            knowledge_status: components["schemas"]["KnowledgeStatus"];
            /** Knowledge Brief */
            knowledge_brief: string;
            /** Knowledge Error */
            knowledge_error: string | null;
            /** Knowledge Generated At */
            knowledge_generated_at: string | null;
            /** Knowledge Stale */
            knowledge_stale: boolean;
            /** Files */
            files: components["schemas"]["KnowledgeFileOut"][];
        };
        /**
         * KnowledgeStatus
         * @enum {string}
         */
        KnowledgeStatus: "empty" | "processing" | "ready" | "error";
        /** LlmConnectOut */
        LlmConnectOut: {
            /** Ok */
            ok: boolean;
            /**
             * Models
             * @default []
             */
            models: string[];
            /** Model */
            model?: string | null;
            /** Error */
            error?: string | null;
        };
        /** LlmTestOut */
        LlmTestOut: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** MeetingDetailOut */
        MeetingDetailOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Title */
            title: string;
            /** Source Filename */
            source_filename: string;
            status: components["schemas"]["MeetingStatus"];
            /** Error Message */
            error_message: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Language */
            language: string | null;
            /** Progress */
            progress: number | null;
            /** Processing Started At */
            processing_started_at: string | null;
            /** Processing Finished At */
            processing_finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Tasks */
            tasks: components["schemas"]["TaskOut"][];
            /** Speaker Labels */
            speaker_labels: {
                [key: string]: string;
            };
            /** Detected Speakers */
            detected_speakers: string[];
        };
        /** MeetingOut */
        MeetingOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Title */
            title: string;
            /** Source Filename */
            source_filename: string;
            status: components["schemas"]["MeetingStatus"];
            /** Error Message */
            error_message: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Language */
            language: string | null;
            /** Progress */
            progress: number | null;
            /** Processing Started At */
            processing_started_at: string | null;
            /** Processing Finished At */
            processing_finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MeetingPatchIn */
        MeetingPatchIn: {
            /** Speaker Labels */
            speaker_labels?: {
                [key: string]: string;
            } | null;
        };
        /**
         * MeetingStatus
         * @enum {string}
         */
        MeetingStatus: "queued" | "processing" | "transcribing" | "extracting" | "done" | "error";
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Color
             * @default #7a0d38
             */
            color: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Description */
            description: string;
            /** Ai Context */
            ai_context: string;
            /** Task Prefix */
            task_prefix: string;
            /** Task Format */
            task_format: string;
            /** Task Language */
            task_language: string;
            /** Task Areas */
            task_areas: string[];
            /** Glossary */
            glossary: string[];
            /** Team */
            team: components["schemas"]["TeamMember"][];
            /** Jira Enabled */
            jira_enabled: boolean;
            /** Jira Static Labels */
            jira_static_labels: string[];
            /** Jira Demo Label */
            jira_demo_label: boolean;
            /** Jira Sprint Field */
            jira_sprint_field: string;
            /** Jira Sprint Id */
            jira_sprint_id: number | null;
            /** Jira Key */
            jira_key: string;
            /** Jira Base Url */
            jira_base_url: string;
            /** Jira Email */
            jira_email: string;
            /** Jira Token Set */
            jira_token_set: boolean;
            /** Jira Token Hint */
            jira_token_hint: string;
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            /** Llm Base Url */
            llm_base_url: string | null;
            knowledge_status: components["schemas"]["KnowledgeStatus"];
            /** Knowledge Brief */
            knowledge_brief: string;
            /** Knowledge Error */
            knowledge_error: string | null;
            /** Knowledge Generated At */
            knowledge_generated_at: string | null;
            /** Knowledge Stale */
            knowledge_stale: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectPatchIn */
        ProjectPatchIn: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
            /** Description */
            description?: string | null;
            /** Ai Context */
            ai_context?: string | null;
            /** Task Prefix */
            task_prefix?: string | null;
            /** Task Format */
            task_format?: string | null;
            /** Task Language */
            task_language?: string | null;
            /** Task Areas */
            task_areas?: string[] | null;
            /** Glossary */
            glossary?: string[] | null;
            /** Team */
            team?: components["schemas"]["TeamMember"][] | null;
            /** Jira Enabled */
            jira_enabled?: boolean | null;
            /** Jira Static Labels */
            jira_static_labels?: string[] | null;
            /** Jira Demo Label */
            jira_demo_label?: boolean | null;
            /** Jira Sprint Field */
            jira_sprint_field?: string | null;
            /** Jira Sprint Id */
            jira_sprint_id?: number | null;
            /** Jira Key */
            jira_key?: string | null;
            /** Jira Base Url */
            jira_base_url?: string | null;
            /** Jira Email */
            jira_email?: string | null;
            /** Jira Api Token */
            jira_api_token?: string | null;
            /** Llm Provider */
            llm_provider?: string | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Base Url */
            llm_base_url?: string | null;
            /** Llm Api Key */
            llm_api_key?: string | null;
        };
        /** SegmentOut */
        SegmentOut: {
            /** Id */
            id: number;
            /** T Start */
            t_start: number;
            /** T End */
            t_end: number;
            /** Text */
            text: string;
            /** Speaker */
            speaker: string | null;
            /** Speaker Display */
            speaker_display: string | null;
        };
        /** TaskCreateIn */
        TaskCreateIn: {
            /** Project Id */
            project_id: number;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Assignee */
            assignee?: string | null;
            /** @default medium */
            priority: components["schemas"]["TaskPriority"];
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Meeting Id */
            meeting_id: number | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Area */
            area: string;
            /** Labels */
            labels: string[];
            /** Assignee */
            assignee: string | null;
            priority: components["schemas"]["TaskPriority"];
            status: components["schemas"]["TaskStatus"];
            /** Source Timestamp */
            source_timestamp: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Jira Issue Key */
            jira_issue_key: string | null;
            /** Jira Synced At */
            jira_synced_at: string | null;
            /** Jira Sync Error */
            jira_sync_error: string | null;
        };
        /** TaskPatchIn */
        TaskPatchIn: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Area */
            area?: string | null;
            /** Labels */
            labels?: string[] | null;
            /** Assignee */
            assignee?: string | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /**
             * Push To Jira
             * @default true
             */
            push_to_jira: boolean;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "low" | "medium" | "high";
        /** TaskScreenshotOut */
        TaskScreenshotOut: {
            /** Id */
            id: number;
            /** Task Id */
            task_id: number;
            /** T Sec */
            t_sec: number;
            /** Position */
            position: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "draft" | "approved" | "done" | "rejected";
        /** TeamMember */
        TeamMember: {
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_meetings_api_meetings_get: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_meeting_api_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_meeting_api_meetings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meeting_api_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_meeting_api_meetings__meeting_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_meeting_api_meetings__meeting_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reextract_meeting_api_meetings__meeting_id__reextract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_media_api_meetings__meeting_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                project_id?: number | null;
                status?: components["schemas"]["TaskStatus"] | null;
                meeting_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_task_api_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jira_preview_api_tasks__task_id__jira_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JiraPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jira_push_api_tasks__task_id__jira_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screenshots_api_tasks__task_id__screenshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskScreenshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screenshot_image_api_tasks__task_id__screenshots__screenshot_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
                screenshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_screenshot_api_tasks__task_id__screenshots__screenshot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
                screenshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_test_api_projects__project_id__llm_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_connect_api_projects__project_id__llm_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmConnectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jira_test_api_projects__project_id__jira_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JiraTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jira_users_api_projects__project_id__jira_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JiraUsersOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsOut"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettingsPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_api_projects__project_id__knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_knowledge_file_api_projects__project_id__knowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_knowledge_file_api_projects__project_id__knowledge_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeFileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_file_api_projects__project_id__knowledge__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_knowledge_api_projects__project_id__knowledge_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
